// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

import 'package:flutter/services.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Enigo>>
abstract class Enigo implements RustOpaqueInterface {
  void button({required Button button, required Direction direction});

  static bool hasPermission({required bool openPrompt}) => RustLib.instance.api
      .crateApiEnigoEnigoHasPermission(openPrompt: openPrompt);

  void key({required PhysicalKeyboardKey key, required Direction direction});

  (int, int) location();

  (int, int) mainDisplay();

  void moveMouse({
    required int x,
    required int y,
    required Coordinate coordinate,
  });

  static Enigo preset() => RustLib.instance.api.crateApiEnigoEnigoPreset();

  void raw({required int keycode, required Direction direction});

  void scroll({required int length, required Axis axis});

  void text({required String text});
}

enum Axis { horizontal, vertical }

enum Button {
  left,
  middle,
  right,
  back,
  forward,
  scrollUp,
  scrollDown,
  scrollLeft,
  scrollRight,
}

enum Coordinate { abs, rel }

enum Direction { press, release, click }
