// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

import 'package:flutter/services.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dart:convert';
import 'dart:math';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'kdbx.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `credentials_empty`, `emit`, `enable_recyclebin`, `from`, `from`, `get`, `impl_action`, `io`, `merge`, `not_found`, `parse_uuid`, `summary`, `xml`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SearchInputParse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `hash`, `into`, `into`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `is_match`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Credentials>>
abstract class Credentials implements RustOpaqueInterface {
  static Credentials formCompositeKey({required List<int> key}) =>
      RustLib.instance.api.crateApiKdbxCredentialsFormCompositeKey(key: key);

  static Credentials from({String? password, Uint8List? keyfile}) => RustLib
      .instance
      .api
      .crateApiKdbxCredentialsFrom(password: password, keyfile: keyfile);

  Uint8List getCompositeKey();

  static Future<Uint8List> randomKeyFile() =>
      RustLib.instance.api.crateApiKdbxCredentialsRandomKeyFile();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Kdbx>>
abstract class Kdbx implements RustOpaqueInterface {
  Future<void> action({required KdbxAction action});

  Future<AutofillDataset> autofillSearch({
    required AutofillMetadata metadata,
    String? entryId,
  });

  void bindEventCallback({
    required FutureOr<void> Function(KdbxEvent) callback,
  });

  static Kdbx create({
    required Credentials credentials,
    KdbxConfig? config,
    String? filepath,
  }) => RustLib.instance.api.crateApiKdbxKdbxCreate(
    credentials: credentials,
    config: config,
    filepath: filepath,
  );

  Future<Uint8List> getAttachment({required int id});

  Future<(EntryData, String)> getAutoTypeSequence({required String id});

  Uint8List getCompositeKey();

  Future<KdbxConfig> getConfig();

  Future<CustomDataItem?> getCustomData({required String key, String? id});

  Future<EntryData> getEntry({required String id, int? historyIndex});

  Future<List<EntryData>> getEntryHistorys({required String id});

  Future<List<EntryData>> getEntrys({
    String? sreach,
    String? groupId,
    bool? ignoreGroupConfig,
    bool? includeRecycle,
    bool? caseSensitive,
  });

  Future<GroupData> getGroup({required String id});

  Future<Map<String, GroupData>> getGroups();

  Future<Meta> getMeta();

  Future<VariantDictionaryValue?> getPublicCustomData({required String key});

  Future<(List<GroupData>, List<EntryData>)> getRecycleItems();

  Future<UpdateMeta> getUpdateMeta();

  Future<MergeLog> merge({required Kdbx kdbx});

  Future<void> modifyPassword({required Credentials credentials});

  EntryData newEntry();

  GroupData newGroup();

  static Future<Kdbx> open({
    required Credentials credentials,
    required String filepath,
  }) => RustLib.instance.api.crateApiKdbxKdbxOpen(
    credentials: credentials,
    filepath: filepath,
  );

  static Future<Kdbx> openBytes({
    required Credentials credentials,
    required List<int> bytes,
    String? filepath,
  }) => RustLib.instance.api.crateApiKdbxKdbxOpenBytes(
    credentials: credentials,
    bytes: bytes,
    filepath: filepath,
  );

  Future<Uint8List> save();

  Future<void> saveFile({String? filepath});

  Future<(FieldSummary, Meta, Map<String, GroupData>)> summary();

  Future<Uint8List> toXml();

  Future<bool> verifyCredentials({required Credentials credentials});
}

enum Argon2Version { version10, version13 }

class Attachment {
  final int id;
  final String name;
  final int size;
  final Uint8List? data;

  const Attachment({
    required this.id,
    required this.name,
    required this.size,
    this.data,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ size.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          data == other.data;
}

class AutoType {
  bool enabled;
  String? defaultSequence;
  DataTransferObfuscation dataTransferObfuscation;
  final List<AutoTypeAssociation> associations;

  AutoType({
    required this.enabled,
    this.defaultSequence,
    required this.dataTransferObfuscation,
    required this.associations,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      defaultSequence.hashCode ^
      dataTransferObfuscation.hashCode ^
      associations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutoType &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          defaultSequence == other.defaultSequence &&
          dataTransferObfuscation == other.dataTransferObfuscation &&
          associations == other.associations;
}

class AutoTypeAssociation {
  final String window;
  final String sequence;

  const AutoTypeAssociation({required this.window, required this.sequence});

  @override
  int get hashCode => window.hashCode ^ sequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutoTypeAssociation &&
          runtimeType == other.runtimeType &&
          window == other.window &&
          sequence == other.sequence;
}

class AutofillDataset {
  bool? unlock;
  bool? manual;
  String? message;
  List<Map<String, String?>> data;

  AutofillDataset({this.unlock, this.manual, this.message, required this.data});

  Map<String, Object?> toJson() => {
    'unlock': unlock,
    "manual": manual,
    'message': message,
    'data': data,
  };

  @override
  int get hashCode =>
      unlock.hashCode ^ manual.hashCode ^ message.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillDataset &&
          runtimeType == other.runtimeType &&
          unlock == other.unlock &&
          manual == other.manual &&
          message == other.message &&
          data == other.data;
}

class AutofillMetadata {
  final bool? manual;
  final String? packageName;
  final String? webDomain;
  final String? webScheme;
  final Set<String> fieldTypes;

  const AutofillMetadata({
    this.manual,
    this.packageName,
    this.webDomain,
    this.webScheme,
    required this.fieldTypes,
  });

  factory AutofillMetadata.fromJson(Map<dynamic, dynamic> json) =>
      AutofillMetadata(
        fieldTypes: (json['fieldTypes'] as Iterable)
            .map((dynamic e) => e as String)
            .toSet(),
        manual: json["manual"] as bool?,
        packageName: json['packageName'] as String?,
        webDomain: json['webDomain'] as String?,
        webScheme: json['webScheme'] as String?,
      );

  @override
  int get hashCode =>
      manual.hashCode ^
      packageName.hashCode ^
      webDomain.hashCode ^
      webScheme.hashCode ^
      fieldTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillMetadata &&
          runtimeType == other.runtimeType &&
          manual == other.manual &&
          packageName == other.packageName &&
          webDomain == other.webDomain &&
          webScheme == other.webScheme &&
          fieldTypes == other.fieldTypes;
}

enum CompressionConfig { none, gZip }

class CustomDataItem {
  final CustomDataValue? value;
  final DateTime? lastModificationTime;

  const CustomDataItem({this.value, this.lastModificationTime});

  @override
  int get hashCode => value.hashCode ^ lastModificationTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomDataItem &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          lastModificationTime == other.lastModificationTime;
}

@freezed
sealed class CustomDataValue with _$CustomDataValue {
  const CustomDataValue._();

  const factory CustomDataValue.string(String field0) = CustomDataValue_String;
  const factory CustomDataValue.binary(Uint8List field0) =
      CustomDataValue_Binary;
}

enum DataTransferObfuscation { none, useClipboard }

class EntryData {
  final String id;
  String parent;
  final Map<String, FieldValue> fields;
  AutoType? autotype;
  final List<String> tags;
  final Times times;
  final Map<String, CustomDataValue?> customData;
  KdbxIcon? icon;
  Color? foregroundColor;
  Color? backgroundColor;
  String? overrideUrl;
  bool qualityCheck;
  String? previousParentGroup;
  final List<Attachment> attachments;

  EntryData.raw({
    required this.id,
    required this.parent,
    required this.fields,
    this.autotype,
    required this.tags,
    required this.times,
    required this.customData,
    this.icon,
    this.foregroundColor,
    this.backgroundColor,
    this.overrideUrl,
    required this.qualityCheck,
    this.previousParentGroup,
    required this.attachments,
  });

  EntryData clone() =>
      RustLib.instance.api.crateApiKdbxEntryDataClone(that: this);

  factory EntryData({required String parent}) =>
      RustLib.instance.api.crateApiKdbxEntryDataNew(parent: parent);

  @override
  int get hashCode =>
      id.hashCode ^
      parent.hashCode ^
      fields.hashCode ^
      autotype.hashCode ^
      tags.hashCode ^
      times.hashCode ^
      customData.hashCode ^
      icon.hashCode ^
      foregroundColor.hashCode ^
      backgroundColor.hashCode ^
      overrideUrl.hashCode ^
      qualityCheck.hashCode ^
      previousParentGroup.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parent == other.parent &&
          fields == other.fields &&
          autotype == other.autotype &&
          tags == other.tags &&
          times == other.times &&
          customData == other.customData &&
          icon == other.icon &&
          foregroundColor == other.foregroundColor &&
          backgroundColor == other.backgroundColor &&
          overrideUrl == other.overrideUrl &&
          qualityCheck == other.qualityCheck &&
          previousParentGroup == other.previousParentGroup &&
          attachments == other.attachments;
}

class FieldSummary {
  final Set<String> urls;
  final Set<String> userNames;
  final Set<String> emails;
  final Set<String> tags;
  final Set<String> customFields;
  final Map<String, Uint8List> customIcons;
  final Set<String> publicCustomData;
  final int totalEntryCount;
  final int totalGroupCount;

  const FieldSummary({
    required this.urls,
    required this.userNames,
    required this.emails,
    required this.tags,
    required this.customFields,
    required this.customIcons,
    required this.publicCustomData,
    required this.totalEntryCount,
    required this.totalGroupCount,
  });

  static Future<FieldSummary> default_() =>
      RustLib.instance.api.crateApiKdbxFieldSummaryDefault();

  @override
  int get hashCode =>
      urls.hashCode ^
      userNames.hashCode ^
      emails.hashCode ^
      tags.hashCode ^
      customFields.hashCode ^
      customIcons.hashCode ^
      publicCustomData.hashCode ^
      totalEntryCount.hashCode ^
      totalGroupCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldSummary &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          userNames == other.userNames &&
          emails == other.emails &&
          tags == other.tags &&
          customFields == other.customFields &&
          customIcons == other.customIcons &&
          publicCustomData == other.publicCustomData &&
          totalEntryCount == other.totalEntryCount &&
          totalGroupCount == other.totalGroupCount;
}

class FieldValue {
  final Uint8List value;
  final Uint8List? salt;

  const FieldValue.raw({required this.value, this.salt});

  factory FieldValue({required String value, bool? protected}) => RustLib
      .instance
      .api
      .crateApiKdbxFieldValueNew(value: value, protected: protected);

  static Uint8List _transformXor(Uint8List a, Uint8List b) {
    assert(a.length == b.length);
    final ret = Uint8List(a.length);
    for (var i = 0; i < a.length; i++) {
      ret[i] = a[i] ^ b[i];
    }
    return ret;
  }

  static final _random = Random.secure();

  static Uint8List _randomBytes(int length) {
    return Uint8List.fromList(
      List.generate(length, (i) => _random.nextInt(0xff)),
    );
  }

  factory FieldValue.protected(String value) {
    final valueBytes = utf8.encode(value);
    final salt = _randomBytes(valueBytes.length);

    return FieldValue.raw(value: _transformXor(valueBytes, salt), salt: salt);
  }

  factory FieldValue.plaintext(String value) {
    return FieldValue.raw(value: utf8.encode(value));
  }

  String get() {
    return utf8.decode(salt != null ? _transformXor(value, salt!) : value);
  }

  @override
  int get hashCode => value.hashCode ^ salt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldValue &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          salt == other.salt;
}

class GroupData {
  final String id;
  String? parent;
  String name;
  String? notes;
  final List<String> tags;
  KdbxIcon? icon;
  final Times times;
  final Map<String, CustomDataValue?> customData;
  bool isExpanded;
  String? defaultAutotypeSequence;
  bool? enableAutotype;
  bool? enableSearching;
  bool? enableDisplay;
  String? lastTopVisibleEntry;
  String? previousParentGroup;
  final bool isRecycleBin;

  GroupData.raw({
    required this.id,
    this.parent,
    required this.name,
    this.notes,
    required this.tags,
    this.icon,
    required this.times,
    required this.customData,
    required this.isExpanded,
    this.defaultAutotypeSequence,
    this.enableAutotype,
    this.enableSearching,
    this.enableDisplay,
    this.lastTopVisibleEntry,
    this.previousParentGroup,
    required this.isRecycleBin,
  });

  factory GroupData({required String parent}) =>
      RustLib.instance.api.crateApiKdbxGroupDataNew(parent: parent);

  @override
  int get hashCode =>
      id.hashCode ^
      parent.hashCode ^
      name.hashCode ^
      notes.hashCode ^
      tags.hashCode ^
      icon.hashCode ^
      times.hashCode ^
      customData.hashCode ^
      isExpanded.hashCode ^
      defaultAutotypeSequence.hashCode ^
      enableAutotype.hashCode ^
      enableSearching.hashCode ^
      enableDisplay.hashCode ^
      lastTopVisibleEntry.hashCode ^
      previousParentGroup.hashCode ^
      isRecycleBin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parent == other.parent &&
          name == other.name &&
          notes == other.notes &&
          tags == other.tags &&
          icon == other.icon &&
          times == other.times &&
          customData == other.customData &&
          isExpanded == other.isExpanded &&
          defaultAutotypeSequence == other.defaultAutotypeSequence &&
          enableAutotype == other.enableAutotype &&
          enableSearching == other.enableSearching &&
          enableDisplay == other.enableDisplay &&
          lastTopVisibleEntry == other.lastTopVisibleEntry &&
          previousParentGroup == other.previousParentGroup &&
          isRecycleBin == other.isRecycleBin;
}

enum InnerCipherConfig { plain, salsa20, chaCha20 }

@freezed
sealed class KdbxAction with _$KdbxAction {
  const KdbxAction._();

  const factory KdbxAction.updateEntry(EntryData field0) =
      KdbxAction_UpdateEntry;
  const factory KdbxAction.updateGroup(GroupData field0) =
      KdbxAction_UpdateGroup;
  const factory KdbxAction.updateMeta(UpdateMeta field0) =
      KdbxAction_UpdateMeta;
  const factory KdbxAction.updateMetaCustomData(
    Map<String, CustomDataValue?> field0,
  ) = KdbxAction_UpdateMetaCustomData;
  const factory KdbxAction.updateConfig({
    OuterCipherConfig? outerCipherConfig,
    CompressionConfig? compressionConfig,
    InnerCipherConfig? innerCipherConfig,
    KdfConfig? kdfConfig,
  }) = KdbxAction_UpdateConfig;
  const factory KdbxAction.move2Trash(List<String> field0) =
      KdbxAction_Move2Trash;
  const factory KdbxAction.delete(List<String> field0) = KdbxAction_Delete;
  const factory KdbxAction.restore(List<String> field0) = KdbxAction_Restore;
  const factory KdbxAction.move2Group({
    required List<String> from,
    required String to,
  }) = KdbxAction_Move2Group;
  const factory KdbxAction.importEntry({
    required List<Map<String, String>> items,
    String? to,
  }) = KdbxAction_ImportEntry;
  const factory KdbxAction.updateSyncEntry([EntryData? field0]) =
      KdbxAction_UpdateSyncEntry;
}

class KdbxConfig {
  final OuterCipherConfig outerCipherConfig;
  final CompressionConfig compressionConfig;
  final InnerCipherConfig innerCipherConfig;
  final KdfConfig kdfConfig;

  const KdbxConfig({
    required this.outerCipherConfig,
    required this.compressionConfig,
    required this.innerCipherConfig,
    required this.kdfConfig,
  });

  @override
  int get hashCode =>
      outerCipherConfig.hashCode ^
      compressionConfig.hashCode ^
      innerCipherConfig.hashCode ^
      kdfConfig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KdbxConfig &&
          runtimeType == other.runtimeType &&
          outerCipherConfig == other.outerCipherConfig &&
          compressionConfig == other.compressionConfig &&
          innerCipherConfig == other.innerCipherConfig &&
          kdfConfig == other.kdfConfig;
}

@freezed
sealed class KdbxError with _$KdbxError implements FrbException {
  const KdbxError._();

  @Implements<FrbBacktracedException>()
  const factory KdbxError.parseUuid({
    required String message,
    required String backtrace,
  }) = KdbxError_ParseUuid;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.notFound({
    required String message,
    required String backtrace,
  }) = KdbxError_NotFound;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.credentialsEmpty({
    required String message,
    required String backtrace,
  }) = KdbxError_CredentialsEmpty;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.io({
    required String message,
    required String backtrace,
  }) = KdbxError_Io;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.incorrectCredentials({
    required String message,
    required String backtrace,
  }) = KdbxError_IncorrectCredentials;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.xml({
    required String message,
    required String backtrace,
  }) = KdbxError_XML;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.invalidKeyFile({
    required String message,
    required String backtrace,
  }) = KdbxError_InvalidKeyFile;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.unknown({
    required String message,
    required String backtrace,
  }) = KdbxError_Unknown;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.unexpectedEof({
    required String message,
    required String backtrace,
  }) = KdbxError_UnexpectedEof;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.invalidKdbxIdentifier({
    required String message,
    required String backtrace,
  }) = KdbxError_InvalidKDBXIdentifier;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.invalidKdbxVersion({
    required String message,
    required String backtrace,
  }) = KdbxError_InvalidKDBXVersion;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.cryptography({
    required String message,
    required String backtrace,
  }) = KdbxError_Cryptography;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.databaseFormat({
    required String message,
    required String backtrace,
  }) = KdbxError_DatabaseFormat;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.generateRandom({
    required String message,
    required String backtrace,
  }) = KdbxError_GenerateRandom;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.duplicateUuid({
    required String message,
    required String backtrace,
  }) = KdbxError_DuplicateUuid;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.moveGroup({
    required String message,
    required String backtrace,
  }) = KdbxError_MoveGroup;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.merge({
    required String message,
    required String backtrace,
  }) = KdbxError_Merge;
  @Implements<FrbBacktracedException>()
  const factory KdbxError.cannotDeleteRoot({
    required String message,
    required String backtrace,
  }) = KdbxError_CannotDeleteRoot;
}

@freezed
sealed class KdbxEvent with _$KdbxEvent {
  const KdbxEvent._();

  const factory KdbxEvent.saved() = KdbxEvent_Saved;
  const factory KdbxEvent.none(String field0) = KdbxEvent_None;
}

@freezed
sealed class KdbxIcon with _$KdbxIcon {
  const KdbxIcon._();

  const factory KdbxIcon.builtIn(int field0) = KdbxIcon_BuiltIn;
  const factory KdbxIcon.custom(String field0, [Uint8List? field1]) =
      KdbxIcon_Custom;
}

class KdbxKey {
  const KdbxKey();

  static const KEY_TITLE = "Title";
  static const KEY_URL = "URL";
  static const KEY_URL1 = "URL1";
  static const KEY_URL2 = "URL2";
  static const KEY_URL3 = "URL3";
  static const KEY_URL4 = "URL4";
  static const KEY_URL5 = "URL5";
  static const KEY_USER_NAME = "UserName";
  static const KEY_EMAIL = "Email";
  static const KEY_PASSWORD = "Password";
  static const KEY_NOTES = "Notes";
  static const KEY_OTP = "OTPAuth";
  static const SPECIAL_KEY_TAGS = "Tags";
  static const SPECIAL_KEY_ATTACH = "Attach";
  static const SPECIAL_KEY_EXPIRES = "Expires";
  static const SPECIAL_KEY_AUTO_TYPE = "AutoType";
  static const SPECIAL_KEY_AUTO_FILL_PACKAGE_NAME = "AutoFillPackageName";
}

@freezed
sealed class KdfConfig with _$KdfConfig {
  const KdfConfig._();

  const factory KdfConfig.aes({required int rounds}) = KdfConfig_Aes;
  const factory KdfConfig.argon2({
    required int iterations,
    required int memory,
    required int parallelism,
    required Argon2Version version,
  }) = KdfConfig_Argon2;
  const factory KdfConfig.argon2Id({
    required int iterations,
    required int memory,
    required int parallelism,
    required Argon2Version version,
  }) = KdfConfig_Argon2id;
}

class MemoryProtection {
  final bool protectTitle;
  final bool protectUsername;
  final bool protectPassword;
  final bool protectUrl;
  final bool protectNotes;

  const MemoryProtection({
    required this.protectTitle,
    required this.protectUsername,
    required this.protectPassword,
    required this.protectUrl,
    required this.protectNotes,
  });

  @override
  int get hashCode =>
      protectTitle.hashCode ^
      protectUsername.hashCode ^
      protectPassword.hashCode ^
      protectUrl.hashCode ^
      protectNotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryProtection &&
          runtimeType == other.runtimeType &&
          protectTitle == other.protectTitle &&
          protectUsername == other.protectUsername &&
          protectPassword == other.protectPassword &&
          protectUrl == other.protectUrl &&
          protectNotes == other.protectNotes;
}

class MergeEvent {
  final MergeEventTarget target;
  final MergeEventType eventType;

  const MergeEvent({required this.target, required this.eventType});

  @override
  int get hashCode => target.hashCode ^ eventType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergeEvent &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          eventType == other.eventType;
}

@freezed
sealed class MergeEventTarget with _$MergeEventTarget {
  const MergeEventTarget._();

  const factory MergeEventTarget.entry(String field0) = MergeEventTarget_Entry;
  const factory MergeEventTarget.group(String field0) = MergeEventTarget_Group;
  const factory MergeEventTarget.icon(String field0) = MergeEventTarget_Icon;
}

enum MergeEventType { created, deleted, locationUpdated, updated }

class MergeLog {
  final bool masterKeyChanged;
  final bool isUpdateMasterKey;
  final List<String> warnings;
  final List<MergeEvent> events;

  const MergeLog({
    required this.masterKeyChanged,
    required this.isUpdateMasterKey,
    required this.warnings,
    required this.events,
  });

  @override
  int get hashCode =>
      masterKeyChanged.hashCode ^
      isUpdateMasterKey.hashCode ^
      warnings.hashCode ^
      events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergeLog &&
          runtimeType == other.runtimeType &&
          masterKeyChanged == other.masterKeyChanged &&
          isUpdateMasterKey == other.isUpdateMasterKey &&
          warnings == other.warnings &&
          events == other.events;
}

class Meta {
  final String? generator;
  final String? databaseName;
  final DateTime? databaseNameChanged;
  final String? databaseDescription;
  final DateTime? databaseDescriptionChanged;
  final String? defaultUsername;
  final DateTime? defaultUsernameChanged;
  final PlatformInt64? maintenanceHistoryDays;
  final Color? color;
  final DateTime? masterKeyChanged;
  final PlatformInt64? masterKeyChangeRec;
  final PlatformInt64? masterKeyChangeForce;
  final MemoryProtection? memoryProtection;
  final bool? recyclebinEnabled;
  final String? recyclebinUuid;
  final DateTime? recyclebinChanged;
  final String? entryTemplatesGroup;
  final DateTime? entryTemplatesGroupChanged;
  final String? lastSelectedGroup;
  final String? lastTopVisibleGroup;
  final PlatformInt64? historyMaxItems;
  final PlatformInt64? historyMaxSize;
  final DateTime? settingsChanged;
  final Set<String> customData;

  const Meta({
    this.generator,
    this.databaseName,
    this.databaseNameChanged,
    this.databaseDescription,
    this.databaseDescriptionChanged,
    this.defaultUsername,
    this.defaultUsernameChanged,
    this.maintenanceHistoryDays,
    this.color,
    this.masterKeyChanged,
    this.masterKeyChangeRec,
    this.masterKeyChangeForce,
    this.memoryProtection,
    this.recyclebinEnabled,
    this.recyclebinUuid,
    this.recyclebinChanged,
    this.entryTemplatesGroup,
    this.entryTemplatesGroupChanged,
    this.lastSelectedGroup,
    this.lastTopVisibleGroup,
    this.historyMaxItems,
    this.historyMaxSize,
    this.settingsChanged,
    required this.customData,
  });

  @override
  int get hashCode =>
      generator.hashCode ^
      databaseName.hashCode ^
      databaseNameChanged.hashCode ^
      databaseDescription.hashCode ^
      databaseDescriptionChanged.hashCode ^
      defaultUsername.hashCode ^
      defaultUsernameChanged.hashCode ^
      maintenanceHistoryDays.hashCode ^
      color.hashCode ^
      masterKeyChanged.hashCode ^
      masterKeyChangeRec.hashCode ^
      masterKeyChangeForce.hashCode ^
      memoryProtection.hashCode ^
      recyclebinEnabled.hashCode ^
      recyclebinUuid.hashCode ^
      recyclebinChanged.hashCode ^
      entryTemplatesGroup.hashCode ^
      entryTemplatesGroupChanged.hashCode ^
      lastSelectedGroup.hashCode ^
      lastTopVisibleGroup.hashCode ^
      historyMaxItems.hashCode ^
      historyMaxSize.hashCode ^
      settingsChanged.hashCode ^
      customData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Meta &&
          runtimeType == other.runtimeType &&
          generator == other.generator &&
          databaseName == other.databaseName &&
          databaseNameChanged == other.databaseNameChanged &&
          databaseDescription == other.databaseDescription &&
          databaseDescriptionChanged == other.databaseDescriptionChanged &&
          defaultUsername == other.defaultUsername &&
          defaultUsernameChanged == other.defaultUsernameChanged &&
          maintenanceHistoryDays == other.maintenanceHistoryDays &&
          color == other.color &&
          masterKeyChanged == other.masterKeyChanged &&
          masterKeyChangeRec == other.masterKeyChangeRec &&
          masterKeyChangeForce == other.masterKeyChangeForce &&
          memoryProtection == other.memoryProtection &&
          recyclebinEnabled == other.recyclebinEnabled &&
          recyclebinUuid == other.recyclebinUuid &&
          recyclebinChanged == other.recyclebinChanged &&
          entryTemplatesGroup == other.entryTemplatesGroup &&
          entryTemplatesGroupChanged == other.entryTemplatesGroupChanged &&
          lastSelectedGroup == other.lastSelectedGroup &&
          lastTopVisibleGroup == other.lastTopVisibleGroup &&
          historyMaxItems == other.historyMaxItems &&
          historyMaxSize == other.historyMaxSize &&
          settingsChanged == other.settingsChanged &&
          customData == other.customData;
}

enum OuterCipherConfig { aes256, twofish, chaCha20 }

class Times {
  final DateTime? creation;
  final DateTime? lastModification;
  final DateTime? lastAccess;
  DateTime? expiry;
  final DateTime? locationChanged;
  bool? expires;
  BigInt? usageCount;

  Times({
    this.creation,
    this.lastModification,
    this.lastAccess,
    this.expiry,
    this.locationChanged,
    this.expires,
    this.usageCount,
  });

  @override
  int get hashCode =>
      creation.hashCode ^
      lastModification.hashCode ^
      lastAccess.hashCode ^
      expiry.hashCode ^
      locationChanged.hashCode ^
      expires.hashCode ^
      usageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Times &&
          runtimeType == other.runtimeType &&
          creation == other.creation &&
          lastModification == other.lastModification &&
          lastAccess == other.lastAccess &&
          expiry == other.expiry &&
          locationChanged == other.locationChanged &&
          expires == other.expires &&
          usageCount == other.usageCount;
}

class UpdateMeta {
  String? databaseName;
  String? databaseDescription;
  String? defaultUsername;
  PlatformInt64? maintenanceHistoryDays;
  Color? color;
  PlatformInt64? masterKeyChangeRec;
  PlatformInt64? masterKeyChangeForce;
  MemoryProtection? memoryProtection;
  String? entryTemplatesGroup;
  String? lastSelectedGroup;
  String? lastTopVisibleGroup;
  PlatformInt64? historyMaxItems;
  PlatformInt64? historyMaxSize;

  UpdateMeta({
    this.databaseName,
    this.databaseDescription,
    this.defaultUsername,
    this.maintenanceHistoryDays,
    this.color,
    this.masterKeyChangeRec,
    this.masterKeyChangeForce,
    this.memoryProtection,
    this.entryTemplatesGroup,
    this.lastSelectedGroup,
    this.lastTopVisibleGroup,
    this.historyMaxItems,
    this.historyMaxSize,
  });

  @override
  int get hashCode =>
      databaseName.hashCode ^
      databaseDescription.hashCode ^
      defaultUsername.hashCode ^
      maintenanceHistoryDays.hashCode ^
      color.hashCode ^
      masterKeyChangeRec.hashCode ^
      masterKeyChangeForce.hashCode ^
      memoryProtection.hashCode ^
      entryTemplatesGroup.hashCode ^
      lastSelectedGroup.hashCode ^
      lastTopVisibleGroup.hashCode ^
      historyMaxItems.hashCode ^
      historyMaxSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateMeta &&
          runtimeType == other.runtimeType &&
          databaseName == other.databaseName &&
          databaseDescription == other.databaseDescription &&
          defaultUsername == other.defaultUsername &&
          maintenanceHistoryDays == other.maintenanceHistoryDays &&
          color == other.color &&
          masterKeyChangeRec == other.masterKeyChangeRec &&
          masterKeyChangeForce == other.masterKeyChangeForce &&
          memoryProtection == other.memoryProtection &&
          entryTemplatesGroup == other.entryTemplatesGroup &&
          lastSelectedGroup == other.lastSelectedGroup &&
          lastTopVisibleGroup == other.lastTopVisibleGroup &&
          historyMaxItems == other.historyMaxItems &&
          historyMaxSize == other.historyMaxSize;
}

@freezed
sealed class VariantDictionaryValue with _$VariantDictionaryValue {
  const VariantDictionaryValue._();

  const factory VariantDictionaryValue.uInt32(int field0) =
      VariantDictionaryValue_UInt32;
  const factory VariantDictionaryValue.uInt64(BigInt field0) =
      VariantDictionaryValue_UInt64;
  const factory VariantDictionaryValue.bool(bool field0) =
      VariantDictionaryValue_Bool;
  const factory VariantDictionaryValue.int32(int field0) =
      VariantDictionaryValue_Int32;
  const factory VariantDictionaryValue.int64(PlatformInt64 field0) =
      VariantDictionaryValue_Int64;
  const factory VariantDictionaryValue.string(String field0) =
      VariantDictionaryValue_String;
  const factory VariantDictionaryValue.byteArray(Uint8List field0) =
      VariantDictionaryValue_ByteArray;
}
