import 'package:flutter/material.dart';
import 'package:kdbx/kdbx.dart';

class KdbxIcon2Material {
  static const icons = [
    Icons.key_rounded,
    Icons.public_rounded,
    Icons.error_rounded,
    Icons.dns_rounded,
    Icons.push_pin_rounded,
    Icons.forum_rounded,
    Icons.extension_rounded,
    Icons.edit_rounded,
    Icons.power_rounded,
    Icons.perm_identity_rounded,
    Icons.attach_file_rounded,
    Icons.camera_rounded,
    Icons.wifi_rounded,
    Icons.link_rounded,
    Icons.battery_3_bar_rounded,
    Icons.qr_code_rounded,
    Icons.star_rounded,
    Icons.album_rounded,
    Icons.monitor_rounded,
    Icons.email_rounded,
    Icons.toggle_on_rounded,
    Icons.content_paste_rounded,
    Icons.send_rounded,
    Icons.tv_rounded,
    Icons.bolt_rounded,
    Icons.inbox_rounded,
    Icons.save_rounded,
    Icons.storage_rounded,
    Icons.adjust_rounded,
    Icons.enhanced_encryption_rounded,
    Icons.terminal_rounded,
    Icons.print_rounded,
    Icons.terminal_rounded,
    Icons.commit_rounded,
    Icons.settings_rounded,
    Icons.computer_rounded,
    Icons.inventory_2_rounded,
    Icons.credit_card_rounded,
    Icons.laptop_windows_rounded,
    Icons.schedule_rounded,
    Icons.mark_email_unread_rounded,
    Icons.flag_rounded,
    Icons.gamepad_rounded,
    Icons.memory_rounded,
    Icons.sticky_note_2_rounded,
    Icons.event_busy_rounded,
    Icons.info_rounded,
    Icons.view_in_ar_rounded,
    Icons.folder_rounded,
    Icons.folder_open_rounded,
    Icons.leaderboard_rounded,
    Icons.lock_open_rounded,
    Icons.lock_rounded,
    Icons.check_rounded,
    Icons.edit_rounded,
    Icons.account_box_rounded,
    Icons.book_rounded,
    Icons.list_alt_outlined,
    Icons.key_rounded,
    Icons.build_rounded,
    Icons.house_rounded,
    Icons.star_rounded,
    Icons.image_not_supported_rounded,
    Icons.location_pin,
    Icons.apple_rounded,
    Icons.image_not_supported_rounded,
    Icons.paid_rounded,
    Icons.calendar_month_rounded,
    Icons.smartphone_rounded,
  ];

  static IconData to(KdbxIcon index) {
    return icons[index.index];
  }
}
