// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

import 'package:flutter/services.dart';

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/enigo.dart';
import 'api/kdbx.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CredentialsPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EnigoPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_KdbxPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ButtonPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Credentials
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    dynamic raw,
  );

  @protected
  Enigo
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    dynamic raw,
  );

  @protected
  Kdbx
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    dynamic raw,
  );

  @protected
  Button
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    dynamic raw,
  );

  @protected
  Enigo
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    dynamic raw,
  );

  @protected
  Kdbx
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    dynamic raw,
  );

  @protected
  Button
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    dynamic raw,
  );

  @protected
  Credentials
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    dynamic raw,
  );

  @protected
  Enigo
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    dynamic raw,
  );

  @protected
  Kdbx
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_NaiveDateTime(dynamic raw);

  @protected
  Color
  dco_decode_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColor(
    dynamic raw,
  );

  @protected
  PhysicalKeyboardKey
  dco_decode_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKey(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(KdbxEvent)
  dco_decode_DartFn_Inputs_kdbx_event_Output_unit_AnyhowException(dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, FieldValue> dco_decode_Map_String_field_value_None(dynamic raw);

  @protected
  Map<String, GroupData> dco_decode_Map_String_group_data_None(dynamic raw);

  @protected
  Map<String, Uint8List> dco_decode_Map_String_list_prim_u_8_strict_None(
    dynamic raw,
  );

  @protected
  Map<String, String?> dco_decode_Map_String_opt_String_None(dynamic raw);

  @protected
  Map<String, CustomDataValue?>
  dco_decode_Map_String_opt_box_autoadd_custom_data_value_None(dynamic raw);

  @protected
  Credentials
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    dynamic raw,
  );

  @protected
  Enigo
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    dynamic raw,
  );

  @protected
  Kdbx
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    dynamic raw,
  );

  @protected
  Button
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    dynamic raw,
  );

  @protected
  Set<String> dco_decode_Set_String_None(dynamic raw);

  @protected
  RustStreamSink<FrbLogRecord> dco_decode_StreamSink_frb_log_record_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Argon2Version dco_decode_argon_2_version(dynamic raw);

  @protected
  Attachment dco_decode_attachment(dynamic raw);

  @protected
  AutoType dco_decode_auto_type(dynamic raw);

  @protected
  AutoTypeAssociation dco_decode_auto_type_association(dynamic raw);

  @protected
  AutofillDataset dco_decode_autofill_dataset(dynamic raw);

  @protected
  AutofillMetadata dco_decode_autofill_metadata(dynamic raw);

  @protected
  Axis dco_decode_axis(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_NaiveDateTime(dynamic raw);

  @protected
  AutoType dco_decode_box_autoadd_auto_type(dynamic raw);

  @protected
  AutofillMetadata dco_decode_box_autoadd_autofill_metadata(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CompressionConfig dco_decode_box_autoadd_compression_config(dynamic raw);

  @protected
  CustomDataItem dco_decode_box_autoadd_custom_data_item(dynamic raw);

  @protected
  CustomDataValue dco_decode_box_autoadd_custom_data_value(dynamic raw);

  @protected
  EntryData dco_decode_box_autoadd_entry_data(dynamic raw);

  @protected
  GroupData dco_decode_box_autoadd_group_data(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  InnerCipherConfig dco_decode_box_autoadd_inner_cipher_config(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_isize(dynamic raw);

  @protected
  KdbxAction dco_decode_box_autoadd_kdbx_action(dynamic raw);

  @protected
  KdbxConfig dco_decode_box_autoadd_kdbx_config(dynamic raw);

  @protected
  KdbxIcon dco_decode_box_autoadd_kdbx_icon(dynamic raw);

  @protected
  KdfConfig dco_decode_box_autoadd_kdf_config(dynamic raw);

  @protected
  MemoryProtection dco_decode_box_autoadd_memory_protection(dynamic raw);

  @protected
  OuterCipherConfig dco_decode_box_autoadd_outer_cipher_config(dynamic raw);

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UpdateMeta dco_decode_box_autoadd_update_meta(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  VariantDictionaryValue dco_decode_box_autoadd_variant_dictionary_value(
    dynamic raw,
  );

  @protected
  CompressionConfig dco_decode_compression_config(dynamic raw);

  @protected
  Coordinate dco_decode_coordinate(dynamic raw);

  @protected
  CustomDataItem dco_decode_custom_data_item(dynamic raw);

  @protected
  CustomDataValue dco_decode_custom_data_value(dynamic raw);

  @protected
  DataTransferObfuscation dco_decode_data_transfer_obfuscation(dynamic raw);

  @protected
  Direction dco_decode_direction(dynamic raw);

  @protected
  EntryData dco_decode_entry_data(dynamic raw);

  @protected
  FieldSummary dco_decode_field_summary(dynamic raw);

  @protected
  FieldValue dco_decode_field_value(dynamic raw);

  @protected
  FrbLogRecord dco_decode_frb_log_record(dynamic raw);

  @protected
  GroupData dco_decode_group_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InnerCipherConfig dco_decode_inner_cipher_config(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  KdbxAction dco_decode_kdbx_action(dynamic raw);

  @protected
  KdbxConfig dco_decode_kdbx_config(dynamic raw);

  @protected
  KdbxError dco_decode_kdbx_error(dynamic raw);

  @protected
  KdbxEvent dco_decode_kdbx_event(dynamic raw);

  @protected
  KdbxIcon dco_decode_kdbx_icon(dynamic raw);

  @protected
  KdbxKey dco_decode_kdbx_key(dynamic raw);

  @protected
  KdfConfig dco_decode_kdf_config(dynamic raw);

  @protected
  List<Map<String, String>> dco_decode_list_Map_String_String_None(dynamic raw);

  @protected
  List<Map<String, String?>> dco_decode_list_Map_String_opt_String_None(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Attachment> dco_decode_list_attachment(dynamic raw);

  @protected
  List<AutoTypeAssociation> dco_decode_list_auto_type_association(dynamic raw);

  @protected
  List<EntryData> dco_decode_list_entry_data(dynamic raw);

  @protected
  List<GroupData> dco_decode_list_group_data(dynamic raw);

  @protected
  List<KdbxAction> dco_decode_list_kdbx_action(dynamic raw);

  @protected
  List<MergeEvent> dco_decode_list_merge_event(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, FieldValue)> dco_decode_list_record_string_field_value(
    dynamic raw,
  );

  @protected
  List<(String, GroupData)> dco_decode_list_record_string_group_data(
    dynamic raw,
  );

  @protected
  List<(String, Uint8List)> dco_decode_list_record_string_list_prim_u_8_strict(
    dynamic raw,
  );

  @protected
  List<(String, CustomDataValue?)>
  dco_decode_list_record_string_opt_box_autoadd_custom_data_value(dynamic raw);

  @protected
  List<(String, String?)> dco_decode_list_record_string_opt_string(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  MemoryProtection dco_decode_memory_protection(dynamic raw);

  @protected
  MergeEvent dco_decode_merge_event(dynamic raw);

  @protected
  MergeEventTarget dco_decode_merge_event_target(dynamic raw);

  @protected
  MergeEventType dco_decode_merge_event_type(dynamic raw);

  @protected
  MergeLog dco_decode_merge_log(dynamic raw);

  @protected
  Meta dco_decode_meta(dynamic raw);

  @protected
  Color?
  dco_decode_opt_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColor(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_NaiveDateTime(dynamic raw);

  @protected
  AutoType? dco_decode_opt_box_autoadd_auto_type(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CompressionConfig? dco_decode_opt_box_autoadd_compression_config(dynamic raw);

  @protected
  CustomDataItem? dco_decode_opt_box_autoadd_custom_data_item(dynamic raw);

  @protected
  CustomDataValue? dco_decode_opt_box_autoadd_custom_data_value(dynamic raw);

  @protected
  EntryData? dco_decode_opt_box_autoadd_entry_data(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  InnerCipherConfig? dco_decode_opt_box_autoadd_inner_cipher_config(
    dynamic raw,
  );

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_isize(dynamic raw);

  @protected
  KdbxConfig? dco_decode_opt_box_autoadd_kdbx_config(dynamic raw);

  @protected
  KdbxIcon? dco_decode_opt_box_autoadd_kdbx_icon(dynamic raw);

  @protected
  KdfConfig? dco_decode_opt_box_autoadd_kdf_config(dynamic raw);

  @protected
  MemoryProtection? dco_decode_opt_box_autoadd_memory_protection(dynamic raw);

  @protected
  OuterCipherConfig? dco_decode_opt_box_autoadd_outer_cipher_config(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  VariantDictionaryValue? dco_decode_opt_box_autoadd_variant_dictionary_value(
    dynamic raw,
  );

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OuterCipherConfig dco_decode_outer_cipher_config(dynamic raw);

  @protected
  (EntryData, String) dco_decode_record_entry_data_string(dynamic raw);

  @protected
  (FieldSummary, Meta, Map<String, GroupData>)
  dco_decode_record_field_summary_meta_map_string_group_data_none(dynamic raw);

  @protected
  (int, int) dco_decode_record_i_32_i_32(dynamic raw);

  @protected
  (List<GroupData>, List<EntryData>)
  dco_decode_record_list_group_data_list_entry_data(dynamic raw);

  @protected
  (String, FieldValue) dco_decode_record_string_field_value(dynamic raw);

  @protected
  (String, GroupData) dco_decode_record_string_group_data(dynamic raw);

  @protected
  (String, Uint8List) dco_decode_record_string_list_prim_u_8_strict(
    dynamic raw,
  );

  @protected
  (String, CustomDataValue?)
  dco_decode_record_string_opt_box_autoadd_custom_data_value(dynamic raw);

  @protected
  (String, String?) dco_decode_record_string_opt_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  Settings dco_decode_settings(dynamic raw);

  @protected
  Times dco_decode_times(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateMeta dco_decode_update_meta(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VariantDictionaryValue dco_decode_variant_dictionary_value(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Credentials
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    SseDeserializer deserializer,
  );

  @protected
  Enigo
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    SseDeserializer deserializer,
  );

  @protected
  Kdbx
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    SseDeserializer deserializer,
  );

  @protected
  Button
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    SseDeserializer deserializer,
  );

  @protected
  Enigo
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    SseDeserializer deserializer,
  );

  @protected
  Kdbx
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    SseDeserializer deserializer,
  );

  @protected
  Button
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    SseDeserializer deserializer,
  );

  @protected
  Credentials
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    SseDeserializer deserializer,
  );

  @protected
  Enigo
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    SseDeserializer deserializer,
  );

  @protected
  Kdbx
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_NaiveDateTime(SseDeserializer deserializer);

  @protected
  Color
  sse_decode_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColor(
    SseDeserializer deserializer,
  );

  @protected
  PhysicalKeyboardKey
  sse_decode_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKey(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, FieldValue> sse_decode_Map_String_field_value_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, GroupData> sse_decode_Map_String_group_data_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, Uint8List> sse_decode_Map_String_list_prim_u_8_strict_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String?> sse_decode_Map_String_opt_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, CustomDataValue?>
  sse_decode_Map_String_opt_box_autoadd_custom_data_value_None(
    SseDeserializer deserializer,
  );

  @protected
  Credentials
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    SseDeserializer deserializer,
  );

  @protected
  Enigo
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    SseDeserializer deserializer,
  );

  @protected
  Kdbx
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    SseDeserializer deserializer,
  );

  @protected
  Button
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    SseDeserializer deserializer,
  );

  @protected
  Set<String> sse_decode_Set_String_None(SseDeserializer deserializer);

  @protected
  RustStreamSink<FrbLogRecord> sse_decode_StreamSink_frb_log_record_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Argon2Version sse_decode_argon_2_version(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer);

  @protected
  AutoType sse_decode_auto_type(SseDeserializer deserializer);

  @protected
  AutoTypeAssociation sse_decode_auto_type_association(
    SseDeserializer deserializer,
  );

  @protected
  AutofillDataset sse_decode_autofill_dataset(SseDeserializer deserializer);

  @protected
  AutofillMetadata sse_decode_autofill_metadata(SseDeserializer deserializer);

  @protected
  Axis sse_decode_axis(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_NaiveDateTime(
    SseDeserializer deserializer,
  );

  @protected
  AutoType sse_decode_box_autoadd_auto_type(SseDeserializer deserializer);

  @protected
  AutofillMetadata sse_decode_box_autoadd_autofill_metadata(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CompressionConfig sse_decode_box_autoadd_compression_config(
    SseDeserializer deserializer,
  );

  @protected
  CustomDataItem sse_decode_box_autoadd_custom_data_item(
    SseDeserializer deserializer,
  );

  @protected
  CustomDataValue sse_decode_box_autoadd_custom_data_value(
    SseDeserializer deserializer,
  );

  @protected
  EntryData sse_decode_box_autoadd_entry_data(SseDeserializer deserializer);

  @protected
  GroupData sse_decode_box_autoadd_group_data(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InnerCipherConfig sse_decode_box_autoadd_inner_cipher_config(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_isize(SseDeserializer deserializer);

  @protected
  KdbxAction sse_decode_box_autoadd_kdbx_action(SseDeserializer deserializer);

  @protected
  KdbxConfig sse_decode_box_autoadd_kdbx_config(SseDeserializer deserializer);

  @protected
  KdbxIcon sse_decode_box_autoadd_kdbx_icon(SseDeserializer deserializer);

  @protected
  KdfConfig sse_decode_box_autoadd_kdf_config(SseDeserializer deserializer);

  @protected
  MemoryProtection sse_decode_box_autoadd_memory_protection(
    SseDeserializer deserializer,
  );

  @protected
  OuterCipherConfig sse_decode_box_autoadd_outer_cipher_config(
    SseDeserializer deserializer,
  );

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UpdateMeta sse_decode_box_autoadd_update_meta(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  VariantDictionaryValue sse_decode_box_autoadd_variant_dictionary_value(
    SseDeserializer deserializer,
  );

  @protected
  CompressionConfig sse_decode_compression_config(SseDeserializer deserializer);

  @protected
  Coordinate sse_decode_coordinate(SseDeserializer deserializer);

  @protected
  CustomDataItem sse_decode_custom_data_item(SseDeserializer deserializer);

  @protected
  CustomDataValue sse_decode_custom_data_value(SseDeserializer deserializer);

  @protected
  DataTransferObfuscation sse_decode_data_transfer_obfuscation(
    SseDeserializer deserializer,
  );

  @protected
  Direction sse_decode_direction(SseDeserializer deserializer);

  @protected
  EntryData sse_decode_entry_data(SseDeserializer deserializer);

  @protected
  FieldSummary sse_decode_field_summary(SseDeserializer deserializer);

  @protected
  FieldValue sse_decode_field_value(SseDeserializer deserializer);

  @protected
  FrbLogRecord sse_decode_frb_log_record(SseDeserializer deserializer);

  @protected
  GroupData sse_decode_group_data(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InnerCipherConfig sse_decode_inner_cipher_config(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  KdbxAction sse_decode_kdbx_action(SseDeserializer deserializer);

  @protected
  KdbxConfig sse_decode_kdbx_config(SseDeserializer deserializer);

  @protected
  KdbxError sse_decode_kdbx_error(SseDeserializer deserializer);

  @protected
  KdbxEvent sse_decode_kdbx_event(SseDeserializer deserializer);

  @protected
  KdbxIcon sse_decode_kdbx_icon(SseDeserializer deserializer);

  @protected
  KdbxKey sse_decode_kdbx_key(SseDeserializer deserializer);

  @protected
  KdfConfig sse_decode_kdf_config(SseDeserializer deserializer);

  @protected
  List<Map<String, String>> sse_decode_list_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  List<Map<String, String?>> sse_decode_list_Map_String_opt_String_None(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Attachment> sse_decode_list_attachment(SseDeserializer deserializer);

  @protected
  List<AutoTypeAssociation> sse_decode_list_auto_type_association(
    SseDeserializer deserializer,
  );

  @protected
  List<EntryData> sse_decode_list_entry_data(SseDeserializer deserializer);

  @protected
  List<GroupData> sse_decode_list_group_data(SseDeserializer deserializer);

  @protected
  List<KdbxAction> sse_decode_list_kdbx_action(SseDeserializer deserializer);

  @protected
  List<MergeEvent> sse_decode_list_merge_event(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, FieldValue)> sse_decode_list_record_string_field_value(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, GroupData)> sse_decode_list_record_string_group_data(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Uint8List)> sse_decode_list_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, CustomDataValue?)>
  sse_decode_list_record_string_opt_box_autoadd_custom_data_value(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String?)> sse_decode_list_record_string_opt_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  MemoryProtection sse_decode_memory_protection(SseDeserializer deserializer);

  @protected
  MergeEvent sse_decode_merge_event(SseDeserializer deserializer);

  @protected
  MergeEventTarget sse_decode_merge_event_target(SseDeserializer deserializer);

  @protected
  MergeEventType sse_decode_merge_event_type(SseDeserializer deserializer);

  @protected
  MergeLog sse_decode_merge_log(SseDeserializer deserializer);

  @protected
  Meta sse_decode_meta(SseDeserializer deserializer);

  @protected
  Color?
  sse_decode_opt_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColor(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_NaiveDateTime(
    SseDeserializer deserializer,
  );

  @protected
  AutoType? sse_decode_opt_box_autoadd_auto_type(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CompressionConfig? sse_decode_opt_box_autoadd_compression_config(
    SseDeserializer deserializer,
  );

  @protected
  CustomDataItem? sse_decode_opt_box_autoadd_custom_data_item(
    SseDeserializer deserializer,
  );

  @protected
  CustomDataValue? sse_decode_opt_box_autoadd_custom_data_value(
    SseDeserializer deserializer,
  );

  @protected
  EntryData? sse_decode_opt_box_autoadd_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InnerCipherConfig? sse_decode_opt_box_autoadd_inner_cipher_config(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_isize(SseDeserializer deserializer);

  @protected
  KdbxConfig? sse_decode_opt_box_autoadd_kdbx_config(
    SseDeserializer deserializer,
  );

  @protected
  KdbxIcon? sse_decode_opt_box_autoadd_kdbx_icon(SseDeserializer deserializer);

  @protected
  KdfConfig? sse_decode_opt_box_autoadd_kdf_config(
    SseDeserializer deserializer,
  );

  @protected
  MemoryProtection? sse_decode_opt_box_autoadd_memory_protection(
    SseDeserializer deserializer,
  );

  @protected
  OuterCipherConfig? sse_decode_opt_box_autoadd_outer_cipher_config(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  VariantDictionaryValue? sse_decode_opt_box_autoadd_variant_dictionary_value(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OuterCipherConfig sse_decode_outer_cipher_config(
    SseDeserializer deserializer,
  );

  @protected
  (EntryData, String) sse_decode_record_entry_data_string(
    SseDeserializer deserializer,
  );

  @protected
  (FieldSummary, Meta, Map<String, GroupData>)
  sse_decode_record_field_summary_meta_map_string_group_data_none(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_i_32_i_32(SseDeserializer deserializer);

  @protected
  (List<GroupData>, List<EntryData>)
  sse_decode_record_list_group_data_list_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  (String, FieldValue) sse_decode_record_string_field_value(
    SseDeserializer deserializer,
  );

  @protected
  (String, GroupData) sse_decode_record_string_group_data(
    SseDeserializer deserializer,
  );

  @protected
  (String, Uint8List) sse_decode_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  (String, CustomDataValue?)
  sse_decode_record_string_opt_box_autoadd_custom_data_value(
    SseDeserializer deserializer,
  );

  @protected
  (String, String?) sse_decode_record_string_opt_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer);

  @protected
  Times sse_decode_times(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateMeta sse_decode_update_meta(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VariantDictionaryValue sse_decode_variant_dictionary_value(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    Credentials self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    Enigo self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    Kdbx self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    Button self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    Enigo self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    Kdbx self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    Button self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    Credentials self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    Enigo self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    Kdbx self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_Chrono_NaiveDateTime(DateTime self, SseSerializer serializer);

  @protected
  void
  sse_encode_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColor(
    Color self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKey(
    PhysicalKeyboardKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_kdbx_event_Output_unit_AnyhowException(
    FutureOr<void> Function(KdbxEvent) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_field_value_None(
    Map<String, FieldValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_group_data_None(
    Map<String, GroupData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_prim_u_8_strict_None(
    Map<String, Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_opt_String_None(
    Map<String, String?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_opt_box_autoadd_custom_data_value_None(
    Map<String, CustomDataValue?> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    Credentials self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    Enigo self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    Kdbx self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    Button self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Set_String_None(Set<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_frb_log_record_Sse(
    RustStreamSink<FrbLogRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_argon_2_version(Argon2Version self, SseSerializer serializer);

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_auto_type(AutoType self, SseSerializer serializer);

  @protected
  void sse_encode_auto_type_association(
    AutoTypeAssociation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_autofill_dataset(
    AutofillDataset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_autofill_metadata(
    AutofillMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_axis(Axis self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_NaiveDateTime(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_auto_type(
    AutoType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_autofill_metadata(
    AutofillMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compression_config(
    CompressionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_custom_data_item(
    CustomDataItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_custom_data_value(
    CustomDataValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_data(
    EntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_data(
    GroupData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_inner_cipher_config(
    InnerCipherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_isize(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_kdbx_action(
    KdbxAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_kdbx_config(
    KdbxConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_kdbx_icon(
    KdbxIcon self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_kdf_config(
    KdfConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_memory_protection(
    MemoryProtection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_outer_cipher_config(
    OuterCipherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_meta(
    UpdateMeta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_variant_dictionary_value(
    VariantDictionaryValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compression_config(
    CompressionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coordinate(Coordinate self, SseSerializer serializer);

  @protected
  void sse_encode_custom_data_item(
    CustomDataItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_data_value(
    CustomDataValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_data_transfer_obfuscation(
    DataTransferObfuscation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_direction(Direction self, SseSerializer serializer);

  @protected
  void sse_encode_entry_data(EntryData self, SseSerializer serializer);

  @protected
  void sse_encode_field_summary(FieldSummary self, SseSerializer serializer);

  @protected
  void sse_encode_field_value(FieldValue self, SseSerializer serializer);

  @protected
  void sse_encode_frb_log_record(FrbLogRecord self, SseSerializer serializer);

  @protected
  void sse_encode_group_data(GroupData self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_inner_cipher_config(
    InnerCipherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_kdbx_action(KdbxAction self, SseSerializer serializer);

  @protected
  void sse_encode_kdbx_config(KdbxConfig self, SseSerializer serializer);

  @protected
  void sse_encode_kdbx_error(KdbxError self, SseSerializer serializer);

  @protected
  void sse_encode_kdbx_event(KdbxEvent self, SseSerializer serializer);

  @protected
  void sse_encode_kdbx_icon(KdbxIcon self, SseSerializer serializer);

  @protected
  void sse_encode_kdbx_key(KdbxKey self, SseSerializer serializer);

  @protected
  void sse_encode_kdf_config(KdfConfig self, SseSerializer serializer);

  @protected
  void sse_encode_list_Map_String_String_None(
    List<Map<String, String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_Map_String_opt_String_None(
    List<Map<String, String?>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment(
    List<Attachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_auto_type_association(
    List<AutoTypeAssociation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_data(
    List<EntryData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_data(
    List<GroupData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_kdbx_action(
    List<KdbxAction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_merge_event(
    List<MergeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_field_value(
    List<(String, FieldValue)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_group_data(
    List<(String, GroupData)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_prim_u_8_strict(
    List<(String, Uint8List)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_opt_box_autoadd_custom_data_value(
    List<(String, CustomDataValue?)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_opt_string(
    List<(String, String?)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_protection(
    MemoryProtection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_event(MergeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_merge_event_target(
    MergeEventTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_event_type(
    MergeEventType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_log(MergeLog self, SseSerializer serializer);

  @protected
  void sse_encode_meta(Meta self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_CustomSerializer_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerColor(
    Color? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_NaiveDateTime(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_auto_type(
    AutoType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_compression_config(
    CompressionConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_custom_data_item(
    CustomDataItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_custom_data_value(
    CustomDataValue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_entry_data(
    EntryData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_inner_cipher_config(
    InnerCipherConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_isize(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_kdbx_config(
    KdbxConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_kdbx_icon(
    KdbxIcon? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_kdf_config(
    KdfConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_memory_protection(
    MemoryProtection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_outer_cipher_config(
    OuterCipherConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_variant_dictionary_value(
    VariantDictionaryValue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_outer_cipher_config(
    OuterCipherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_entry_data_string(
    (EntryData, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_field_summary_meta_map_string_group_data_none(
    (FieldSummary, Meta, Map<String, GroupData>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_32_i_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_record_list_group_data_list_entry_data(
    (List<GroupData>, List<EntryData>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_field_value(
    (String, FieldValue) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_group_data(
    (String, GroupData) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_list_prim_u_8_strict(
    (String, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_opt_box_autoadd_custom_data_value(
    (String, CustomDataValue?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_opt_string(
    (String, String?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_times(Times self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_meta(UpdateMeta self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_variant_dictionary_value(
    VariantDictionaryValue self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCredentials(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEnigo(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKdbx(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInner_Button(
    int ptr,
  );
}
