name: rpass
description: "A new Flutter project."
publish_to: "none"
version: 3.0.0+300000
resolution: workspace
homepage: https://github.com/GodCount/rpass-flutter.git

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.35.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 路由
  auto_route: ^10.3.0

  # 日志
  logging: ^1.3.0
  logging_appenders: ^1.4.0+1

  # 数据存储
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0

  # 密码管理相关
  kdbx:
    path: ../../packages/kdbx.dart
  crypto: ^3.0.3
  otp: ^3.1.4
  uuid: ^4.4.0

  # biometric_storage: ^5.1.1-dev.2
  # 可以关闭 android 硬件级加密,提高兼容性
  # https://github.com/authpass/biometric_storage/pull/139
  biometric_storage:
    git:
      url: https://github.com/kee-org/biometric_storage
      ref: 29860ebed7d23ec2fd09749728ef12b285420758

  # 网络和数据传输
  dio: ^5.9.0
  webdav_client:
    path: ../../packages/webdav_client
  lan_fill_server:
    path: ../../packages/lan_fill_server

  # 文件处理
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  path: ^1.9.1
  csv: ^6.0.0

  # UI 组件和动画
  cupertino_icons: ^1.0.8
  animations: ^2.1.0
  animated_flip_counter: ^0.3.4
  flutter_slidable: ^4.0.3
  pretty_qr_code: ^3.6.0
  flutter_context_menu: ^0.3.0
  rich_text_controller: ^3.0.1

  # 扫码功能
  mobile_scanner: ^7.1.2

  # 系统集成和窗口管理
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  hotkey_manager: ^0.2.3
  enigo_flutter:
    path: ../../packages/enigo_flutter
  common_native_channel:
    path: ../../packages/common_native_channel

  # 工具和实用功能
  intl: ^0.20.2
  url_launcher: ^6.3.2

  # 代码生成
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
