name: Build macOS

on:
  workflow_dispatch:
  workflow_call:

env:
  FLUTTER_VERSION: "3.38.10"

jobs:
  build_macos:
    name: "Release for MacOS"
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - uses: bluefireteam/melos-action@v3

      - name: Build MacOS
        run: |
          cd apps/rpass
          flutter build macos --release

      - name: Create DMG
        run: |
          mkdir -p build/dist/macos
          cp -a apps/rpass/build/macos/Build/Products/Release/Rpass.app build/dist/macos
          ln -s /Applications build/dist/macos/Applications
          hdiutil create -format UDZO -srcfolder build/dist/macos -volname Rpass Rpass.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v7
        with:
          name: macos_outputs
          path: Rpass.dmg
